local STRINGS = GLOBAL.STRINGS

 --STRINGS.NAMES : 지정할 이름 
 --DESCRIBE : 말하게 하는 명령어

STRINGS.CHARACTER_TITLES.sendi = "센디(인간) *전용기"
STRINGS.CHARACTER_NAMES.sendi = "센디"
STRINGS.CHARACTER_DESCRIPTIONS.sendi = "*평범한 체력과 데미지\n*화룡과의 친화 :: 마력을이용한 모닥불 제조\n*허기를 소모한 작은 광원효과.\n\n*전용 회피기와  돌진기[V/V+Sh]\n*까다로운 식성과 수많은 전용장비"
STRINGS.CHARACTER_QUOTES.sendi = "\"어서 다른분들을 찾으러 가야해요!\""

STRINGS.CHARACTER_TITLES.anan = "아난(늑대)"
STRINGS.CHARACTER_NAMES.anan = "Anan"
STRINGS.CHARACTER_DESCRIPTIONS.anan = "*허기에 따른 공격&스피드 증가, 공복 가속\n*사냥꾼 :: 저렴한 덫 레시피와 육포제조\n*악몽연료를 이용해 보석전환\n\n*하운드가 공격하지 않습니다.\n*미칠경우 비선공 동물들이 그를 노립니다."
STRINGS.CHARACTER_QUOTES.anan = "\"킁,킁.. 낯선 냄세야..\n어서 동료들을 찾아야겠어.\""

STRINGS.CHARACTER_TITLES.tees = "티스(독잇뱀) *전용기"
STRINGS.CHARACTER_NAMES.tees = "Tees"
STRINGS.CHARACTER_DESCRIPTIONS.tees = "* 연약한 체력과 데미지\n* 시간차 강력한 독데미지\n* 독잇뱀 :: 저렴한 다트 레시피\n*대부분의 적들이 그를 무시합니다\n전용 무적기와 지속형 일격기 \n*타인에게 정신력 오라"
STRINGS.CHARACTER_QUOTES.tees = "\"우웅.. 다들 어디있는거야?\""


STRINGS.NAMES.SENDISEDMASK = "센디의 눈물 마스크"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDISEDMASK = "메시지가 쓰여있어..\n [더이상 아무것도 하고싶지않아]"
--센디 마스크
STRINGS.NAMES.SENDI_HAT_CROWN = "프랜드 폭시 헬멧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_HAT_CROWN = "여우모자?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_HAT_CROWN = "모두가 저를 인정해줄거에요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_HAT_CROWN = "난 늑대야! 여우가 아니라고!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_HAT_CROWN = "우웅? 이제 돼지랑 친구할수있어?"
--군주의 왕관
STRINGS.NAMES.SENDI_HAT_GOGGLES = "군주의 고글"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_HAT_GOGGLES = "이 고글은... 매우 과학적이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_HAT_GOGGLES = "좋아. 이제 준비가 되었어."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_HAT_GOGGLES = "눈치껏 행동하는게 심상에 좋을거다."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_HAT_GOGGLES = "이 제국의 왕은 나당!"
--프랜드 고글
STRINGS.NAMES.SENDI_HAT_SPIDER = "스파이더 캣쿤 헬멧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_HAT_SPIDER = "고양이귀가 달린 거미라.."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_HAT_SPIDER = "..이건 고양이다, 고양이다, 고양이다.."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_HAT_SPIDER = "...여우에 이어 고양이라니."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_HAT_SPIDER = "냐옹!"
--프랜드 고글



STRINGS.NAMES.SENDI_ARMOR_01 = "센디의 니트갑옷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_ARMOR_01 = "작은 소녀의 옷이야." 
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_ARMOR_01 = "이 머플러, 사실은 제 옷이에요!" 
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_ARMOR_01 = "센디누나의 손재주는 알아줘야해." 
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_ARMOR_01 = "우히히, 이거 엄청 따뜻하당!" 

--센디 아머
STRINGS.NAMES.SENDI_ARMOR_02 = "센디의 라이프아머"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_ARMOR_02 = "작은 소녀의 푸른옷이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_ARMOR_02 = "기존의 갑옷의 갑옷보다 조금더 튼튼하고 효율적으로 만들었어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_ARMOR_02 = "푸른색이 도는게 마음에 드는데?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_ARMOR_02 = "우히히, 이거 엄청 따뜻하당! 시원하기까지해!"

--센디 라이프 아머


STRINGS.NAMES.SENDI_AMULET = "영롱한 아뮬렛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_AMULET = "아름다운 목걸이에요." 
--아뮬렛 sendi_amulet
--



STRINGS.NAMES.SENDI_RAPIER = "센디의 레이피어"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_RAPIER = "찌르는것보다 휘두르는것에 초점이 맞춰진 레이피어야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_RAPIER = "제가 애용하던것과 닮은 레이피어에요!/n수제지만 예쁘죠?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_RAPIER = "또 한번 부러뜨렸다간 누나의 손에..."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_RAPIER = "적들을 꼬치구이로 만들어주자!"

--센디 레이피어
STRINGS.NAMES.SENDI_RAPIER_WOOD = "연습용 목재 레이피어"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_RAPIER_WOOD = "나무와 풀의 걸작이지."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_RAPIER_WOOD = "연습할때 쓰던걸 본따 만들었어요. 그래도 쓸만 하다구요!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_RAPIER_WOOD = "센디누나가 훈련할때 사용하는 레이피어야. 힘조절을 해야해."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_RAPIER_WOOD = "이걸로 열밤 훈련하면 더 강해질 수 있어!"

--센디 연습용 목재 레이피어
STRINGS.NAMES.SENDI_RAPIER_IGNIA = "이그니아 레이피어"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_RAPIER_IGNIA = "이 불은 왜 꺼지지않는거야?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_RAPIER_IGNIA = "끊임없이 타오르고있어요...\n 방대한 에너지가 느껴져요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_RAPIER_IGNIA = "이건.. 이건 너무 뜨겁잖아!\n저주를 받은것이 분명해!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_RAPIER_IGNIA = "이거 완전 멋있어! 엄청 좋은 무기야!"

--센디 이그니아 레이피어



STRINGS.NAMES.SENDIPACK = "센디의 책가방"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDIPACK = "과학이 접목된 작은소녀의 가방이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDIPACK = "제가 저로써 남아있을 수 있게 해주는 가방이에요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDIPACK = "이건 아주 유용한 배낭이에요."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDIPACK = "나한텐 조금 무거워."

--센디팩


--센디 오븐
STRINGS.NAMES.SENDI_OVEN = "센디의 오븐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_OVEN = "아주 과학적인 아궁이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_OVEN = "돌을 하나하나 쌓아올렸어요!\n이제 음식들을 넣어 조리해먹을수 있어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_OVEN = "같은 아궁이에서.. 어떻게 두가지 속성의 불이 나오는거야?\n역시 마법은 굉장해!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_OVEN = "어른이 없을때 만지면 나쁜어린이야!"

--센디 오두막
STRINGS.NAMES.SENDIOBJECT_HUT = "모두의 오두막" --sendiobject_hut
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDIOBJECT_HUT = "...그들이 나보다 낫군.\n 뭐..? 나도 사용할 수 있다고?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDIOBJECT_HUT = "너무너무 아득한 저희들의 집이에요!\n...어라, 이그니아?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDIOBJECT_HUT = "그리운 냄세가 나."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDIOBJECT_HUT = "나 여기 너무너무 좋아! 따뜻행!"
--센디 창고
STRINGS.NAMES.SENDIOBJECT_WAREHOUSE = "모두의 창고" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDIOBJECT_WAREHOUSE = "오... 넉넉하게 잘 들어가겠어."
STRINGS.CHARACTERS.SENDI.SENDIOBJECT_WAREHOUSE = "이것저것 잔뜩 담을 수 있어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDIOBJECT_WAREHOUSE = "이것도 넣고, 저것도 넣고."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDIOBJECT_WAREHOUSE = "으응! 정리정돈은 중요해!"
--식량고
STRINGS.NAMES.SENDIOBJECT_ICEBOX = "모두의 냉장고" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDIOBJECT_ICEBOX = "오.. 음식도 넉넉하게 잘 들어가겠는데?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDIOBJECT_WAREHOUSE = "다양한 식재료를 신선하게 보관할 수 있어요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDIOBJECT_WAREHOUSE = "이 안을 고기로 가득 채우는거야."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDIOBJECT_WAREHOUSE = "맛있는거 맛있는거!"

STRINGS.NAMES.SENDIOBJECT_SALTBOX = "소금 식량고" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDIOBJECT_SALTBOX = "이거.. 음식들이 소금에 절여지는거 아니야?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDIOBJECT_SALTBOX = "우와, 엄청 많이 들어가요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDIOBJECT_SALTBOX = "이 안을 누나의 요리로 가득..!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDIOBJECT_SALTBOX = "행복이 가득한 상자!"

---[[ 아난 물품
STRINGS.ANANTABNAME = "아난탭"

STRINGS.NAMES.ANAN_DAGGER = "부러진 늑대의 단검"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANAN_DAGGER = "이거 괜찮은거야?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.ANAN_DAGGER = "이거 날 반쪽이.."
STRINGS.CHARACTERS.ANAN.DESCRIBE.ANAN_DAGGER = "으르릉..."
STRINGS.CHARACTERS.TEES.DESCRIBE.ANAN_DAGGER = "나처럼 쪼끄매!"

--아난 대거 [부러진]  ANAN_DAGGER
STRINGS.NAMES.ANAN_DAGGER_HARD = "늑대의 단검"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANAN_DAGGER_HARD = "이게 단검이라고?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANAN_DAGGER_HARD = "차가운 냉기가 느껴져요"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANAN_DAGGER_HARD = "익숙한 그립감이야."
STRINGS.CHARACTERS.TEES.DESCRIBE.ANAN_DAGGER_HARD = "우우.. 이거 차가워, 싫어.."


--북쪽늑대 대거  ANAN_DAGGER_WOLF
STRINGS.NAMES.ANAN_DAGGER_WOLF = "북쪽 늑대의 단검"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANAN_DAGGER_WOLF = "이게 진짜 단검이라고?\n냉장고 안에 있는것같아."
STRINGS.CHARACTERS.SENDI.DESCRIBE.ANAN_DAGGER_WOLF = "서걱 서걱한 얼음의 마력이 느껴져요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.ANAN_DAGGER_WOLF = "익숙한 냄새가 나, 그리워"
STRINGS.CHARACTERS.TEES.DESCRIBE.ANAN_DAGGER_WOLF = "너무 추워! 안쓸래!"

--북쪽늑대 대거  ANAN_DAGGER_WOLF

STRINGS.RECIPE_DESC.ANAN_DAGGER = "하아, 이걸 써야아하나.." --rope
STRINGS.RECIPE_DESC.ANAN_DAGGER_HARD = "이걸 여기서도 만들다니!."
STRINGS.RECIPE_DESC.ANAN_DAGGER_WOLF = "이걸 여기서도 만들다니!."

STRINGS.RECIPE_DESC.MEAT_DRIED = "피를 뺐더니.. 양이 줄어버렷네?"
STRINGS.RECIPE_DESC.SMALLMEAT_DRIED = "양에 기별도 가지 않지만.."
STRINGS.RECIPE_DESC.SMALLMEAT = "털에붙은 고기를 모아봤어."
STRINGS.RECIPE_DESC.MEAT = "뼈에붙은 고기를 모아봤어."
STRINGS.RECIPE_DESC.REDGEM = "작은 마술. 굉장하지?" --nightmarefuel
STRINGS.RECIPE_DESC.BLUEGEM = "작은 마술. 굉장하지?"
STRINGS.RECIPE_DESC.GREENGEM = "작은 마술. 굉장하지?"
STRINGS.RECIPE_DESC.PURPLEGEM = "작은 마술. 굉장하지?"
--]]

---[[ 티스
STRINGS.NAMES.TEES_HAT01 = "리틀마우스"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEES_HAT01 = "리틀은 날 지켜주는 친구야!."

STRINGS.TEESTABNAME = "티스탭"

STRINGS.NAMES.TEES_PICKAXE = "허접한 독꽹이"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEES_PICKAXE = "엄청 간지나는 도끼."
STRINGS.CHARACTERS.SENDI.DESCRIBE.TEES_PICKAXE = "티스군의 도끼에요. 네? 독꽹이라구요?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.TEES_PICKAXE = "티스에게 빌려왔어.\n이제 모든 나무를 쓰러뜨리는거야."
STRINGS.CHARACTERS.TEES.DESCRIBE.TEES_PICKAXE = "나무를 벨수있어!\n손잡이가 해지면, 풀로 수리하래!"

STRINGS.RECIPE_DESC.TEES_PICKAXE = "나무를 능숙하게 벨수있어요!"

STRINGS.NAMES.TEES_PICKAXE2 = "멋있는 독꽹이"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEES_PICKAXE2 = "엄청 간지나는 도끼.\n...돌도 쪼개진다고?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.TEES_PICKAXE2 = "티스군의 독꽹이에요.\n..이럴수가! 돌도 쪼갤수있어요!!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.TEES_PICKAXE2 = "티스에게 빌려왔어. \n이제 돌까지 깨부수는거야."
STRINGS.CHARACTERS.TEES.DESCRIBE.TEES_PICKAXE2 = "돌도 부수고, 나무도 벨수있어!\n손잡이가 해지면, 풀로 수리하래!"

STRINGS.RECIPE_DESC.TEES_PICKAXE2 = "돌,나무를 능숙하게 분쇄하세요!"

STRINGS.NAMES.TEES_PICKAXE3 = "짱짱 멋진 독꽹이"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEES_PICKAXE3 = "이건... 병기가 분명해!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.TEES_PICKAXE3 = "티스군의 독꽹이에요!\n이제 뭐든지 깨부술 수 있어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.TEES_PICKAXE3 = "티스에게 빌려왔어. \n이제 세상도 깨부술 수 있을까?"
STRINGS.CHARACTERS.TEES.DESCRIBE.TEES_PICKAXE3 = "더욱 빠르게 돌도 부수고, 나무도 벨수있어!\n손잡이가 해지면, 풀로 수리하래!"
STRINGS.RECIPE_DESC.TEES_PICKAXE3 = "돌,나무를 빠르게 분쇄하세요!"

--]]

---[[시드탭
STRINGS.AOSTABNAME = "시드탭"
STRINGS.OVENTABNAME = "오븐탭"

STRINGS.NAMES.AOS_SENDIPACK = "센디의 책가방"
STRINGS.RECIPE_DESC.AOS_SENDIPACK = "냉장고 기능이 달린 가방!"
STRINGS.NAMES.AOS_SENDI_HAT_CROWN = "프랜드 폭시 헬멧"
STRINGS.RECIPE_DESC.AOS_SENDI_HAT_CROWN = "수인들과 친구가 된다!"
STRINGS.NAMES.AOS_SENDI_ARMOR_01 = "센디의 니트갑옷"
STRINGS.RECIPE_DESC.AOS_SENDI_ARMOR_01 = "따뜻하고, 빨라지는 옷!"
STRINGS.NAMES.AOS_ANAN_DAGGER_HARD = "늑대의 단검"
STRINGS.RECIPE_DESC.AOS_ANAN_DAGGER_HARD = "순간이동 단검!"
STRINGS.NAMES.AOS_TEES_PICKAXE2 = "멋있는 독꽹이"
STRINGS.RECIPE_DESC.AOS_TEES_PICKAXE2 = "돌과 나무를 능숙하게 분쇄하자!"

--]]

--크리에이시드 aos_seed  SEED_CREESEED
STRINGS.NAMES.AOS_SEED = "크리에이시드" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED = "하얀 돌."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED = "순수한 마력이 느껴져요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED = "순수한 마력이 느껴져!"
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED = "뭔가 느껴져!"

STRINGS.NAMES.AOS_SEED_PURPLE = "오염된 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_PURPLE = "..빨간 돌.\n들고있으면 왠지... 화가 나는것같아."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_PURPLE = "오염이 꽤 진행되긴 했지만\n시간이 지나면 원래모습을 되찾을거에요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_PURPLE = "...으르릉, 이거 기분나빠."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_PURPLE = "기분나쁜게 느껴져!"


STRINGS.NAMES.AOS_SEED_BLACK = "매우 오염된 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BLACK = "윽..! 내가 왜 이딴 생활을 반복해야 하는거야?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BLACK = "윽..! 너무나도 끔찍한 마력이에요!\n ...시간이 지나면 괜찮아지겠죠..?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BLACK = "으르릉...!! 아르르르!!!\n 워월월워!!" 
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BLACK = "너무너무 기븐나빠!!"


STRINGS.NAMES.AOS_SEED_BOSS_BLACK = "심연의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_BLACK = "고급스러운 검은 돌. 장식용으로 쓸까?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_BLACK = "이렇게 순수한 마기는 처음이에요.\n 이정도 농도임에도 전혀 위해가 되지 않다니.."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_BLACK = "이렇게 순수한 마기는 처음이야..\n 이정도 농도임에도 전혀 위해가 되지 않다니.."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_BLACK = "엄청 예쁜 검은돌맹이야!"

STRINGS.NAMES.AOS_SEED_BOSS_ORANGE = "태양의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_ORANGE = "어쩐지 뜨뜻하구만."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_ORANGE = "위대한 태양의 마력이 느껴져요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_ORANGE = "들고있으면 더워."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_ORANGE = "헤헤, 이거 들고있으면 따뜻하당!"


STRINGS.NAMES.AOS_SEED_BOSS_RED = "불꽃의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_RED = "완전히 불덩어리구만!!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_RED = "이그니아와 같은 마력의 기운이에요..\n...이그니아?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_RED = "이건 들고있으면 너무 뜨거워!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_RED = "조금 더울지도..!"


STRINGS.NAMES.AOS_SEED_BOSS_SKY = "눈의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_SKY = "한여름에 들고다녀도 춥겠어!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_SKY = "순수한 얼음의 마력이 느껴져요."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_SKY = "익숙한듯한 순수한 마력이 느껴져."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_SKY = "이거 너무 차가워!"


STRINGS.NAMES.AOS_SEED_BOSS_WHITE = "탐욕의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_WHITE = "새하얀 돌.. 어째선지 안에서 목소리가 들리는것같군."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_WHITE = "이렇게 탐욕스러운 마력은 처음이에요.\n...이대로 두다간 저까지 위험해질거에요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_WHITE = "왜 그때..\n그녀석들을 죽이지 못했을까."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_WHITE = "..."

STRINGS.NAMES.AOS_SEED_BOSS_AUTUMN = "풍요의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_AUTUMN = "갈색 돌."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_AUTUMN = "따뜻하고 부드러운 마력이 가득해요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_AUTUMN = "따뜻하고 부드러운 마력이 느껴져"
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_AUTUMN = "부드럽고 기분좋아~"

STRINGS.NAMES.AOS_SEED_BOSS_GREEN = "생명의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_GREEN = "초록색 돌이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_GREEN = "그리운 생명의 마력이 느껴져요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_GREEN = "그리운 마력이 느껴져."
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_GREEN = "그리운 기분이 들어."


STRINGS.NAMES.AOS_SEED_BOSS_YELLOW = "행복의 시드 결정" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_BOSS_YELLOW = "노란색 돌!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_BOSS_YELLOW = "무엇이든 해낼수 있을것만 같은 기분이에요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_BOSS_YELLOW = "드디어 얻어냈어!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_BOSS_YELLOW = "해냈다!!"


STRINGS.NAMES.AOS_SEED_MIDDLE = "거대한 시드 조각" --SEED_CREESEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AOS_SEED_MIDDLE = "조금 큰가?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.AOS_SEED_MIDDLE = "방대한 마력이 느껴져요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.AOS_SEED_MIDDLE = "꽤 많은 마력이 느껴져!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.AOS_SEED_MIDDLE = "조금 큰 하얀돌이야!"


--일반 오브젝트 
STRINGS.NAMES.CAMPFIRE = "따끈따끈 모닥불" 
STRINGS.RECIPE_DESC.CAMPFIRE = "짠, 불씨를 붙혔어요." 

STRINGS.NAMES.TORCH = "한손 횃불" 
STRINGS.RECIPE_DESC.TORCH = "짠, 불씨를 붙혔어요." 

STRINGS.NAMES.CHARCOAL = "친환경 숯" 
STRINGS.RECIPE_DESC.CHARCOAL = "짠, 나무를 태워봤어요!" 

STRINGS.NAMES.TWIGS = "나뭇가지" 
STRINGS.RECIPE_DESC.TWIGS = "짠, 통나무를 조각냈어요!" 

--음식
STRINGS.NAMES.SENDI_FOOD_COCOAPOWDER = "마법의 가루" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_COCOAPOWDER = "핥을때마다 다양한 맛이나. 이건뭐지?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_COCOAPOWDER = "이 가루는 요리에 넣으면, 어울리는 맛으로 변화해요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_COCOAPOWDER = "핥으면 고기맛이나기도 해."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_COCOAPOWDER = "히히, 달콤해!!"


STRINGS.NAMES.SENDI_FOOD_RICEWHEAT = "벼리밀" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_RICEWHEAT = "풀들사이에서 발견했어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_RICEWHEAT = "풀들을 잘 살펴보니 찾을 수 있었어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_RICEWHEAT = "풀을 씹다가 찾아냈어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_RICEWHEAT = "멍뭉이랑 풀을 씹다가 찾아냈어!"


STRINGS.NAMES.SENDI_FOOD_MILK_STRONG = "튼튼 밀크" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_MILK_STRONG = "조금 부족하지만, 든든한 음료지."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_MILK_STRONG = "몸에 좋은 우유에요, 다양한 제빵에 사용돼요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_MILK_STRONG = "그냥 소의 젖이잖아?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_MILK_STRONG = "맛있어!"

  --재료
  
  
STRINGS.NAMES.SENDI_FOOD_COCOA_CUP = "달콤한 얼음컵" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_COCOA_CUP = "아직 차가운 얼음컵이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_COCOA_CUP = "컵에 재료를 담았어요. \n오븐에 넣으면 따뜻해질거에요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_COCOA_CUP = "컵에 재료를 담았어. \n오븐에 넣어 마무리하자."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_COCOA_CUP = "컵에 뭐가 들었어!. \n난로에 넣어볼까?"

STRINGS.NAMES.SENDI_FOOD_COCOA = "따뜻한 코코아" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_COCOA = "들고있었더니 녹았어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_COCOA = "전투 후 따뜻하게 한잔~\n하루를 마무리 하기에 이것만한것이 없지요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_COCOA = "뜨거워서 별로야."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_COCOA = "따뜻하구 달콤해! 맛있어!"

STRINGS.NAMES.SENDI_FOOD_COCOA_COLD = "시원한 코코아" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_COCOA_COLD = "얼음이 떠다니는 코코아라..!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_COCOA_COLD = "얼음이 동동 떠다니는 시원한 코코아 랍니다!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_COCOA_COLD = "와드득 와드득, 식감도좋고, 맛도좋고!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_COCOA_COLD = "끄응~ 머리속이 울려! 근데 맛있다!"


STRINGS.NAMES.SENDI_FOOD_WOLFSTEAK = "하운드 스테이크" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_WOLFSTEAK = "오.. 이건 아직 덜익은거같은데?."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_WOLFSTEAK = "윽... 역한 고기를 접시에 담았어요. \n 오븐에서 한번 더 마무리 해야겠어요."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_WOLFSTEAK = "지금도 솔직히 나쁘진않아. \n 오븐에서 한번 더 마무리 할까?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_WOLFSTEAK = "이거 아직 익지않았어! \n 오븐에 넣어서 구워먹자!."


STRINGS.NAMES.SENDI_FOOD_WOLFSTEAK_COOKED = "허브를 곁들인 북쪽늑대 스테이크" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_WOLFSTEAK_COOKED = "아직 잡내가 남아있지만, 아주 맛있어!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_WOLFSTEAK_COOKED = "아직 잡내가 남아있지만, 아주 맛있어요!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_WOLFSTEAK_COOKED = "아주 맛있어!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_WOLFSTEAK_COOKED = "이거 맛있어!"


STRINGS.NAMES.SENDI_FOOD_BREAD = "빵" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD = "이걸 이곳에서 다시 먹게되다니!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD = "가장 기본적인 식사에요.\n 하지만 이것만먹으면 심심하죠?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD = "빵만 먹고 살순없어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD = "우유랑 같이먹을래!"

STRINGS.NAMES.SENDI_FOOD_SALAD_BANANA = "이끼바나 샐러드" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_SALAD_BANANA = "바나나 샐러드라, 좋은데?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_SALAD_BANANA = "신선한 야채와 바나나의 만남!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_SALAD_BANANA = "달콤한 풀 샐러드."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_SALAD_BANANA = "맛있구 시원해!"


STRINGS.NAMES.SENDI_FOOD_JUICE_LIGHT_BERRY = "빛나는 푸른 주스"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_JUICE_LIGHT_BERRY = "급한대로 양손에쥐고 짰어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_JUICE_LIGHT_BERRY = "급한대로, 양손에 쥐고 꼭 짜봤어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_JUICE_LIGHT_BERRY = "급한대로 양손에쥐고 짰어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_JUICE_LIGHT_BERRY = "양손에쥐고 짰어!"

STRINGS.NAMES.SENDI_FOOD_PIE_LIGHT_BERRY = "푸른파이 반죽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY = "음.. 아직 반죽상태야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY = "얼른 맛있게 구워졌으면 좋겠어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY = "얼른 맛있게 구워졌으면 좋겠어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY = "얼른 구워죠!"

STRINGS.NAMES.SENDI_FOOD_PIE_LIGHT_BERRY_COOKED = "빛나는 베리파이" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY_COOKED = "완벽한 맛이야!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY_COOKED = "불로 구워내니 달콤해졌어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY_COOKED = "불로 구워내니 달콤해졌어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_PIE_LIGHT_BERRY_COOKED = "으음~ 달콤해!!!"

STRINGS.NAMES.SENDI_FOOD_CAKE_BANANA = "바나나 반죽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_CAKE_BANANA = "음.. 아직 반죽상태야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_CAKE_BANANA = "얼른 맛있게 구워졌으면 좋겠어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_CAKE_BANANA = "얼른 맛있게 구워졌으면 좋겠어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_CAKE_BANANA = "얼른 구워죠!"

STRINGS.NAMES.SENDI_FOOD_CAKE_BANANA_COOKED = "바나나 롤케익" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_CAKE_BANANA_COOKED = "시원하고, 폭신하고. 게다가 부드럽기까지 해!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_CAKE_BANANA_COOKED = "아주아주 달콤하고 부드러운 간식이죠!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_CAKE_BANANA_COOKED = "달콤하고 부드러운 간식이야."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_CAKE_BANANA_COOKED = "달콤하고 폭신해!!"

STRINGS.NAMES.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "파란 푸딩" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "이거 상한거 아니야?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "조금 식혔다 먹으면 맛있을거에요!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "이거.. 정말 먹어도 괜찮나?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "얼른 먹을랭!!\n모..? 식혀야해? 왜애!?"


STRINGS.NAMES.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA_COOKED = "허니퐁 푸딩" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA_COOKED = "오븐에 넣었더니 노랗게 되었어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA_COOKED = "냉장고에 차게 식혔더니, 맛있는 푸딩이 되었어요!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA_COOKED = "이제 먹을수 있겠다!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA_COOKED = "숟가락 숟가락 숟가락!!"

STRINGS.NAMES.SENDI_FOOD_RICE_EEL = "장어와 밥" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_RICE_EEL = "장어가 전혀 익지않았어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_RICE_EEL = "밥을 짓다보니 장어가 조금 식어버렸네요..\n 얼른 데워봐요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_RICE_EEL = "솔직히 난 지금도 맛있을거같아!\n...데워야해?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_RICE_EEL = "얼른 구워서 먹자!"

STRINGS.NAMES.SENDI_FOOD_RICE_EEL_COOKED = "장어 덮밥" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_RICE_EEL_COOKED = "헬스해지는 기분이야!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_RICE_EEL_COOKED = "장어의 힘이 불끈 불끈이에요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_RICE_EEL_COOKED = "기운이 펄펄나!\n아올옳!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_RICE_EEL_COOKED = "나 엄청열심히 뛰어놀 수 있을것 같아!"

--3차음식[지상]
STRINGS.NAMES.SENDI_FOOD_BREAD_SAUSAGE = "소세지 빵" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_SAUSAGE = "빵과 소시지는 언제나 진리지!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_SAUSAGE = "맛있는 소시지를 빵에 끼웠어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_SAUSAGE = "빵에 고기를 끼워먹는건 좋은생각인데요, 누나?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_SAUSAGE = "이거 너무너무 맛있어! 최고야!!"

STRINGS.NAMES.SENDI_FOOD_BREAD_MUFFIN = "머핀 반죽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN = "음.. 아직 반죽상태야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN = "얼른 맛있게 구워졌으면 좋겠어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN = "얼른 맛있게 구워졌으면 좋겠어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN = "얼른 구워죠!"

STRINGS.NAMES.SENDI_FOOD_BREAD_MUFFIN_COOKED = "버터 풀- 머핀" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN_COOKED = "..다행히 나비는 초콜릿이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN_COOKED = "건강에좋은 나비 머핀이에요! \n 데코는 초콜릿이랍니다."
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN_COOKED = "맛있겠다.\n...네? 이거 먹으면 죽는다구요?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_MUFFIN_COOKED = "맛있겠다!!\n응? 멍멍이는 이거 먹으면안돼? 왜애?"


STRINGS.NAMES.SENDI_FOOD_RICE_TUNA = "재료를 담은 그릇" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_RICE_TUNA = "생선이 전혀 익지않았어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_RICE_TUNA = "밥을 짓다보니 생선이 조금 식어버렸네요..\n 얼른 데워봐요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_RICE_TUNA = "솔직히 난 지금도 맛있을거같아!\n...데워야해?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_RICE_TUNA = "얼른 구워서 먹자!"

STRINGS.NAMES.SENDI_FOOD_RICE_TUNA_COOKED = "참치 비빔밥" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_RICE_TUNA_COOKED = "이건.. 꽤나 이색적이군!"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_RICE_TUNA_COOKED = "몸에좋고 맛도 좋답니다!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_RICE_TUNA_COOKED = "어떻게 오븐에 들어갔다 나오면.. 뼈가 발라져있는거야?!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_RICE_TUNA_COOKED = "바다의 힘이 가득한 맛이야!"

STRINGS.NAMES.SENDI_FOOD_BREAD_BUT = "식빵 반죽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_BUT = "음.. 아직 반죽상태야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_BUT = "얼른 맛있게 구워졌으면 좋겠어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_BUT = "얼른 맛있게 구워졌으면 좋겠어."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_BUT = "얼른 구워죠!"

STRINGS.NAMES.SENDI_FOOD_BREAD_BUT_COOKED = "호토리 식빵" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_BUT_COOKED = "고향이 떠오르는 식빵이군."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_BUT_COOKED = "견과류를 듬뿍 넣었어요. 건강에 좋고 맛있답니다!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_BUT_COOKED = "씨와 씨로만든 빵..!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_BUT_COOKED = "우유랑 먹을래, 우유!"

--5차음식

STRINGS.NAMES.SENDI_FOOD_CHICKEN = "하얗게 숨은 닭고기" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_CHICKEN = "튀김반죽이야. 손에 묻을정도로 질척해."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_CHICKEN = "튀김옷을 입혔어요!\n 앗, 생고기니까, 날로먹으면 큰일나요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_CHICKEN = "질척질척해서 먹고싶지 않아."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_CHICKEN = "얼른 구워죠!"

STRINGS.NAMES.SENDI_FOOD_CHICKEN_COOKED = "쳐도른 치킨" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_CHICKEN_COOKED = "깊은 올리브유의 향기와 절묘한 치즐링...\n아아, 행복하다."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_CHICKEN_COOKED = "올리브와~ 치킨이 만나 \n 기분이 좋아~"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_CHICKEN_COOKED = "끼애앵..! 입안에서 육즙이 흘러넘치고 있어!\n맛있어어어..!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_CHICKEN_COOKED = "바삭바삭한 고기, 최고로 맛있어~!"

STRINGS.NAMES.SENDI_FOOD_PIE_BERRY = "베리 듬뿍 반죽" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PIE_BERRY = "베리가 아낌없이 들어갔군. 오븐에 넣어서 마무리 하자.?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_PIE_BERRY = "베리를 아낌없이 얹은 파이에요!\n 오븐에 넣어서 마무리 해볼까요?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_PIE_BERRY = "붉은 열매가 가득 들어있어! 오븐에 넣어서 마무리해요 누나!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_PIE_BERRY = "우와아, 파이야! 파이! 얼른 구워죠!!"

STRINGS.NAMES.SENDI_FOOD_PIE_BERRY_COOKED = "감동파이" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_PIE_BERRY_COOKED = "베리가 듬뿍 올려져 있어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_PIE_BERRY_COOKED = "베리가 듬뿍 올려져있어요! 어떤 맛이 날까요?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_PIE_BERRY_COOKED = "달콤할것같은데 조금 셔."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_PIE_BERRY_COOKED = "으으.. 시다아."

STRINGS.NAMES.SENDI_FOOD_DUMPLING = "속보이는 만두피" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_BREAD_BUT = "아직 익지않았어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_BREAD_BUT = "쟈근 만두피에 속을 아낌없이!\n 아아, 먹음직스럽지만 날로먹으면 안돼요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_BREAD_BUT = "그냥 먹으면 안돼는거야?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_BREAD_BUT = "이거 내가 열심히 빚었다! 누나가 구워준대!"

STRINGS.NAMES.SENDI_FOOD_DUMPLING_COOKED = "통통 만두" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_DUMPLING_COOKED = "이 안엔 행복이 가득하다더군."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_DUMPLING_COOKED = "쫄깃 쫄깃~ 야들 야들! 맛있는 만두에요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_DUMPLING_COOKED = "오.. 쫄깃한식감이 재미있어!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_DUMPLING_COOKED = "야들야들하구~.. 핫뜨!, 마시써!"

--6차음식
STRINGS.NAMES.SENDI_FOOD_TANGHURU_BERRY = "베리 탕후루" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_TANGHURU_BERRY = "벌침이 박힌 사탕이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_TANGHURU_BERRY = "베리를 으깨서 설탕옷을 입혔어요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_TANGHURU_BERRY = "티스에게주면 좋아하겠네."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_TANGHURU_BERRY = "달콤한 사탕!!"

STRINGS.NAMES.SENDI_FOOD_STEW_BEEP = "비프스튜" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_STEW_BEEP = "스튜의 재료가 담겨져있어."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_STEW_BEEP = "재료 손질 끝! 오븐에 데워먹으면 돼요!!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_STEW_BEEP = "도대체 왜 고기를 물에 담구는거야?!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_STEW_BEEP = "이거 언제 먹을수 있어?"

STRINGS.NAMES.SENDI_FOOD_STEW_BEEP_COOKED = "비프-스튜" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_STEW_BEEP_COOKED = "행복한날에 먹을수있는 최고의 음식이지."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_STEW_BEEP_COOKED = "비프-스튜, 비-프스튜!\n얼른 먹자구요!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_STEW_BEEP_COOKED = "물에 담근 고기가 이렇게 맛있는 냄세를 내다니!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_STEW_BEEP_COOKED = "김이 모락모락 올라와서 재미있어!!"

STRINGS.NAMES.SENDI_FOOD_MARATANG_BAT = "박쥐 접시" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_MARATANG_BAT = "이걸 먹자고? 거짓말이지?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_MARATANG_BAT = "급할땐 좋은 식량이니까, 매운열매를 넣고 끓이면 어떨까요?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_MARATANG_BAT = "도대체 왜 자꾸 고기를 물에 담구는거에요 누나!?!/n...불에 굽자구요? 끓이는게아니라?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_MARATANG_BAT = "이건... 못먹는 음식이야!\n..웅? 구워보자구?"

STRINGS.NAMES.SENDI_FOOD_MARATANG_BAT_COOKED = "엽기적인 마라탕" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_MARATANG_BAT_COOKED = "오.. 와우, 비주얼이 끝장이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_MARATANG_BAT_COOKED = "어디서부터 잘못된걸까요? 내 레시피는 완벽했는데!"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_MARATANG_BAT_COOKED = "그러니까.. 고기를 물에 담구는건 좋은방법이 아니라고 그랬잖아요!!"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_MARATANG_BAT_COOKED = "이거.. 싫어. 맛없을것같앙!"

STRINGS.NAMES.SENDI_FOOD_MARATANG_FROG = "개구리 접시" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_MARATANG_FROG = "이걸 먹자고? 거짓말이지?"
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_MARATANG_FROG = "급할땐 좋은 식량이니까.. 개구리다리는 나름..\n괜찮지 않을까요?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_MARATANG_FROG = "누나 우선 진정하고 그 다리부터 내려놔요.\n...끓이자구요? 진심으로?"
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_MARATANG_FROG = "누나.. 티스 시러해..\n..웅? 이것도 구워보자구??"

STRINGS.NAMES.SENDI_FOOD_MARATANG_FROG_COOKED = "개굴개굴 마라탕" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SENDI_FOOD_MARATANG_FROG_COOKED = "오.. 와우, 비주얼이 압도적이야."
STRINGS.CHARACTERS.SENDI.DESCRIBE.SENDI_FOOD_MARATANG_FROG_COOKED = "이 요리는 실패했어요. 외형적으로도, 맛으로도...\n 네? 맛있다구요? 정말루..?"
STRINGS.CHARACTERS.ANAN.DESCRIBE.SENDI_FOOD_MARATANG_FROG_COOKED = "이건 정말.... 응? 냄세가 왜 좋은거지.."
STRINGS.CHARACTERS.TEES.DESCRIBE.SENDI_FOOD_MARATANG_FROG_COOKED = "분명.. 분명 맛없게생겼는데!"

--일반오브젝트 제작대사 설정
STRINGS.SENDITABNAME = "센디탭"
--모자
STRINGS.RECIPE_DESC.SENDISEDMASK = "아픈건 싫어 [높은방어율,우산]"
STRINGS.RECIPE_DESC.SENDI_HAT_CROWN = "우린 모두 친구![고기무시]"
STRINGS.RECIPE_DESC.SENDI_HAT_GOGGLES = "사막도 두렵지않아요!"
STRINGS.RECIPE_DESC.SENDI_HAT_SPIDER = "거미 심리학(거미와 친구가됩니다)"
--무기
STRINGS.RECIPE_DESC.SENDI_RAPIER_WOOD = "센디의 연습용 레이피어 입니다."
STRINGS.RECIPE_DESC.SENDI_RAPIER = "센디의 레이피어 입니다."
STRINGS.RECIPE_DESC.SENDI_RAPIER_IGNIA = "활활 타오르고 있어요![불꽃지속딜]" 
--갑옷
STRINGS.RECIPE_DESC.SENDI_ARMOR_01 = "따뜻하고, 몸이 가벼워집니다." 
STRINGS.RECIPE_DESC.SENDI_ARMOR_02 = "더욱 따뜻하고, 가벼워집니다." 
--악세사리
STRINGS.RECIPE_DESC.SENDIPACK = "냉장고 기능이 달린 가방입니다."
STRINGS.RECIPE_DESC.SENDI_AMULET = "목걸이 입니다." 
--오브젝트제작
STRINGS.RECIPE_DESC.SENDI_OVEN = "불꽃의 마법사. 우클릭 변경[오븐+냉장고]" 
STRINGS.RECIPE_DESC.SENDIOBJECT_HUT = "그리운 우리들의 집 [추가장비제작]" --SENDIOBJECT_HUT
STRINGS.RECIPE_DESC.SENDIOBJECT_WAREHOUSE = "많은 물건을 보관하세요!" --SENDIOBJECT_HUT
STRINGS.RECIPE_DESC.SENDIOBJECT_ICEBOX = "음식들을 신선하게!" --SENDIOBJECT_HUT
STRINGS.RECIPE_DESC.SENDIOBJECT_SALTBOX = "소금으로 더 신선하게!" --SENDIOBJECT_HUT
--시드제작
STRINGS.RECIPE_DESC.AOS_SEED = "마력을 실채화 해봅시다!" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.AOS_SEED_PURPLE = "오염된 마력을 추출해봅시다!" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.AOS_SEED_BLACK = "끔찍한 마력을 추출해봅시다!" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.AOS_SEED_MIDDLE = "작은 조각들을 모아볼까요?"
STRINGS.RECIPE_DESC.AOS_SEED_BOSS_YELLOW = "드디어 때가 되었어요!" 

--1차음식
STRINGS.RECIPE_DESC.SENDI_FOOD_MILK_STRONG = "요리에 필요한 우유를 합성해봐요!" --밀크
STRINGS.RECIPE_DESC.SENDI_FOOD_COCOAPOWDER = "달콤한 분말을 얻으세요!" --분말
STRINGS.RECIPE_DESC.SENDI_FOOD_RICEWHEAT = "고기만으론 버틸 수 없어!" --벼리밀
--2차음식
STRINGS.RECIPE_DESC.SENDI_FOOD_COCOA_CUP = "컵에 재료를 넣으세요![exp]" --코코아컵   
STRINGS.RECIPE_DESC.SENDI_FOOD_WOLFSTEAK = "접시 위에서 마법을 부려봅시다![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_BREAD = "약소한 한끼로 최적이죠![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_SALAD_BANANA = "접시위서 먹음직스럽게!![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_JUICE_LIGHT_BERRY = "어서 착즙해볼까요?[exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_PIE_LIGHT_BERRY = "반죽 후 오븐에서 식혀주세요![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_CAKE_BANANA = "반죽 후 오븐에서 구워주세요![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_PUDDING_LIGHT_BERRYBANANA = "반죽후 오븐에서 구워주세요![exp]" --크리에이시드 aos_seed  SEED_CREESEED
STRINGS.RECIPE_DESC.SENDI_FOOD_RICE_EEL = "손질 후 오븐에서 데워주세요![exp]"
--3차 음식
STRINGS.RECIPE_DESC.SENDI_FOOD_BREAD_SAUSAGE = "한끼 식사로 최고에요![exp]"
STRINGS.RECIPE_DESC.SENDI_FOOD_BREAD_MUFFIN = "반죽 후 오븐에서 구워주세요![exp]"
STRINGS.RECIPE_DESC.SENDI_FOOD_BREAD_BUT = "반죽 후 오븐에서 구워주세요![exp]"
STRINGS.RECIPE_DESC.SENDI_FOOD_RICE_TUNA = "손질 후 오븐에서 데워주세요![exp]"
--5차 음식 
STRINGS.RECIPE_DESC.SENDI_FOOD_CHICKEN = "입히고, 오븐에서 구워주세요[EXP]"
STRINGS.RECIPE_DESC.SENDI_FOOD_PIE_BERRY = "반죽 후 오븐에서 구워주세요![EXP]"
STRINGS.RECIPE_DESC.SENDI_FOOD_DUMPLING = "빚어서 오븐에서 구워주세요![EXP]"
--6차음식
STRINGS.RECIPE_DESC.SENDI_FOOD_TANGHURU_BERRY = "설탕물을 입혀주세요![EXP]"
STRINGS.RECIPE_DESC.SENDI_FOOD_STEW_BEEP = "오븐에 팔팔 끓여주세요![EXP]"
--블랙푸드
STRINGS.RECIPE_DESC.SENDI_FOOD_MARATANG_BAT = "오븐에 팔팔 끓여주세요![EXP]"
STRINGS.RECIPE_DESC.SENDI_FOOD_MARATANG_FROG = "오븐에 팔팔 끓여주세요![EXP]"

STRINGS.ACTIONS.AOSMILK = "우유 짜기"
STRINGS.DESCRIBE_CANMILK = "우유를 짤 수 있어."
STRINGS.DESCRIBE_MILK_LEFT = "우유짜기 남은 시간 : "
STRINGS.DESCRIBE_SECOND = "초"

STRINGS.LEVEL = "레벨"
STRINGS.EXP = "경험치"
------- 각 캐릭터들의 음식 먹었을때 대사
STRINGS.CHARACTERS.WARLY.ONEATSENDIFOOD = {
--왈리

}

STRINGS.CHARACTERS.WATHGRITHR.ONEATSENDIFOOD = { 
--위그 프리드

}

STRINGS.CHARACTERS.WAXWELL.ONEATSENDIFOOD = {
--맥스웰
}

STRINGS.CHARACTERS.WEBBER.ONEATSENDIFOOD = {
-- 웨버

}

STRINGS.CHARACTERS.WENDY.ONEATSENDIFOOD = {
--웬디
}

STRINGS.CHARACTERS.WICKERBOTTOM.ONEATSENDIFOOD = {
--위커바텀
}

STRINGS.CHARACTERS.WILLOW.ONEATSENDIFOOD = {
--윌로우
}

STRINGS.CHARACTERS.GENERIC.ONEATSENDIFOOD = { -- "윌슨" 및 다른 대사가 정해지지 않은 모드 케릭터
TEST = "맛있다.",
          COCOAPOWDER = "..Damn it! It's all on my neck!",
          RICEWHEAT = "These prickly thorns cling to your neck!",
          MILK_STRONG = "This milk is excellent. \n I feel like I'm being healthy.",
          COCOA_CUP = "Uh, ice is being chewed raw.",
          COCOA = "It's very sweet, it's nourishing the brain.",
          COCOA_COLD = "It's extremely cold and sobering.",
          WOLFSTEAK = "It's not cooked yet!",
          WOLFSTEAK_COOKED = "Cooking monster meat like this ... \n Wolf meat?",
          --2Dash food 
          BREAD = "And this...",
          SALAD_BANANA = "It's not bad to eat grass and fruit.",
          JUICE_LIGHT_BERRY = "It tastes better than I thought.",
          PIE_LIGHT_BERRY = "You're not done yet!",
          PIE_LIGHT_BERRY_COOKED = "It's sweet and very delicious.",
          CAKE_BANANA = "It's not cooked yet!",
          CAKE_BANANA_COOKED = "The sweet smell of bananas mixes in your \n mouth. It's delicious.",
          PUDDING_LIGHT_BERRYBANA = "Really, your stomach feels a little sore?",
          PUDDING_LIGHT_BERRYBANA_COOKED = "Very sweet. \n It's feeding deep into the brain.", 
          RICE_EEL = "Nothing has been cooked yet!",
          RICE_EEL_COOKED = "The taste and nutrition of eels is already scientifically known. \n It's very delicious.",
          --3rd food
          BREAD_SAUSAGE = " Between bread and bread, the texture of a stiff sausage \n exclaims.",
          BREAD_MUFFIN = "None is baked yet!",
          BREAD_MUFFIN_COOKED = "Though there is a piece of worm in it, her recipe is excellent.",
          BREAD_BUT = "None is baked yet!!",
          BREAD_BUT_COOKED = "And this...",
          --Five food
          RICE_TUNA = "Regarding... It's not cooked yet!\n Don't bother!",
          RICE_TUNA_COOKED = "It reminds me of the taste of eels eaten underground, \n but a little spicy. Is it the taste of Asia?",
          CHICKEN = "These chickens are not cooked at all!",
          CHICKEN_COOKED = "The inside is moist, the outside is crispy. Very good.",
          PIE_BERRY = "None is baked yet!!",
          PIE_BERRY_COOKED = "It's new to do something that I used to eat only as a jam.",
          DUMPLING = "This block of flour is not cooked at all!",
          DUMPLING_COOKED = "Fluid juices are spreading in your mouth.\n What a fantastic taste.",
        
} 

STRINGS.CHARACTERS.WINONA.ONEATSENDIFOOD = {
--위노나
}

STRINGS.CHARACTERS.WOLFGANG.ONEATSENDIFOOD = {
--볼프강
}

STRINGS.CHARACTERS.WOODIE.ONEATSENDIFOOD = {
--우디
}

STRINGS.CHARACTERS.WORMWOOD.ONEATSENDIFOOD = {
--웜우드
}

STRINGS.CHARACTERS.WORTOX.ONEATSENDIFOOD = {
--워톡스
}

STRINGS.CHARACTERS.WX78.ONEATSENDIFOOD = {
--칠팔이
          
}